language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  yarn build
before_deploy:
  - cd build
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true